### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [pilcrowonpaper/oslo-vscode#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by pilcrowOnPaper** [comment]
Hi, thanks!

How does copyright work around here?

**Comment by pilcrowonpaper** [comment]
Thanks!
Yeah, I'll do that. I wasn't expecting this much attention.
